# Generated by Django 3.2.20 on 2023-11-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dynamic_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('howtowork', models.TextField()),
                ('title', models.TextField()),
                ('banner', models.TextField()),
                ('Adress', models.TextField()),
                ('admin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='send_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=50)),
                ('PhoneNumber', models.IntegerField()),
                ('Name', models.TextField()),
            ],
        ),
    ]
